version: '3'

services:
  finance:
    container_name: finance
    build: ./finance/
    entrypoint: ['sh', '/data/web/finance_setup.sh']
    volumes:
      - ./finance:/data/web
      - finance_static:/assets
      - financestatus:/finance_status
    working_dir: /data/web
    restart: always
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - PRODUCTION=True
      - HOST=finance.flowygo.com
    depends_on:
      - financemongodb1
    

  financemongodb3:
    image: mongo:4
    restart: always
    container_name: financemongodb3
    env_file:
      - .env
    volumes:
      - financemongodata3:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsfinance", "--bind_ip_all", "--wiredTigerCacheSizeGB", "0.2" ]
    
  financemongodb2:
    image: mongo:4
    restart: always
    container_name: financemongodb2
    env_file:
      - .env
    volumes:
      - financemongodata2:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsfinance", "--bind_ip_all", "--wiredTigerCacheSizeGB", "0.2"]
      
    
  financemongodb1:
    image: mongo:4
    restart: always
    container_name: financemongodb1
    env_file:
      - .env
    volumes:
      - financemongodata1:/data/db
    expose:
      - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rsfinance", "--bind_ip_all", "--wiredTigerCacheSizeGB", "0.2"]
  
  financemongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    container_name: "financemongosetup"
    depends_on:
      - financemongodb1
    volumes:
      - financestatus:/data/

  financenginx:
    build: ./nginx-pagespeed/
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/app/nginx.conf
      - ./nginx/conf:/etc/nginx/app/conf_app/
      - finance_static:/assets
      - ./finance/_static:/static
      - ./nginx/certificate:/ssl
    expose:
      - "80"
      - "443"
    environment:
      - MAKE_J=4
      - NGINX_VERSION=1.19.2
      - PAGESPEED_VERSION=1.14.36.1
      - LIBPNG_VERSION=1.6.37
      - NGINX_INCLUDE_PATH=/etc/nginx/app/conf_app/*.conf
      - NGINX_DEFAULT_SERVER=off
      - NGINX_FASTCGI_GEOIP=off
      - NGINX_PAGESPEED=on
      - NGINX_PAGESPEED_IMG=on
      - NGINX_PAGESPEED_JS=on
      - NGINX_PAGESPEED_CSS=on
      - NGINX_PAGESPEED_STORAGE=file
      - VIRTUAL_HOST=finance.flowygo.com
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    depends_on:
      - finance

  financeredis:
    container_name: "financeredis"
    image: redis:alpine
    expose:
      - "6379"
    restart: always
    sysctls:
      net.core.somaxconn: '4096' 
        
  celeryfinance:
    container_name: "celeryfinance"
    build: ./finance/
    command: celery -A finance worker -B -l INFO --concurrency=3
    working_dir: /code
    env_file:
      - .env
    volumes:
      - ./finance:/code
    depends_on:
      - financemongodb1
      - financeredis


volumes:
    finance_static:
    financemongodata1:
    financemongodata2:
    financemongodata3:
    financestatus:

networks:
  default: 
    external:
      name: ngix-proxy_default
